// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLYuidKb74NS2e8ZRhBzi6eFQODhoUJyc',
    appId: '1:598435078298:web:0c1cb9676c5e128b06bf23',
    messagingSenderId: '598435078298',
    projectId: 'fir-auth-d52a7',
    authDomain: 'fir-auth-d52a7.firebaseapp.com',
    storageBucket: 'fir-auth-d52a7.firebasestorage.app',
    measurementId: 'G-R5N6P4KD6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCAiJJerq5BZhz1uUNztlydRsZgqRxuho',
    appId: '1:598435078298:android:d13be18dd1859ee806bf23',
    messagingSenderId: '598435078298',
    projectId: 'fir-auth-d52a7',
    storageBucket: 'fir-auth-d52a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVEtsLaQuyl1XT5A6Cnq8WY_HPGEp1hts',
    appId: '1:598435078298:ios:f6f552261ae8c98a06bf23',
    messagingSenderId: '598435078298',
    projectId: 'fir-auth-d52a7',
    storageBucket: 'fir-auth-d52a7.firebasestorage.app',
    iosBundleId: 'com.example.week5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVEtsLaQuyl1XT5A6Cnq8WY_HPGEp1hts',
    appId: '1:598435078298:ios:f6f552261ae8c98a06bf23',
    messagingSenderId: '598435078298',
    projectId: 'fir-auth-d52a7',
    storageBucket: 'fir-auth-d52a7.firebasestorage.app',
    iosBundleId: 'com.example.week5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLYuidKb74NS2e8ZRhBzi6eFQODhoUJyc',
    appId: '1:598435078298:web:be4b7d675f32fbeb06bf23',
    messagingSenderId: '598435078298',
    projectId: 'fir-auth-d52a7',
    authDomain: 'fir-auth-d52a7.firebaseapp.com',
    storageBucket: 'fir-auth-d52a7.firebasestorage.app',
    measurementId: 'G-LN11GQV67X',
  );
}
